#!/bin/sh

# Simple Twitter backup script
# http://blog.jphpsf.com/2012/05/07/backing-up-your-twitter-account-with-t

# Twitter CLI
# https://github.com/sferik/t

export DAY=`date +'%Y-%m-%d'`

echo "Backing up tweets..."
t timeline @tiagofernandez --csv --number 3200 > tweets-$DAY.csv

echo "Backing up retweets..."
t retweets --csv --number 3200 > retweets-$DAY.csv

echo "Backing up replies..."
t replies --csv --number 3200 > replies-$DAY.csv

echo "Backing up favorites..."
t favorites --csv --number 3200 > favorites-$DAY.csv

echo -e "\nBacked up the following:"
echo -e "- "`wc -l tweets-$DAY.csv|cut -d" " -f 1`" tweets"
echo -e "- "`wc -l retweets-$DAY.csv|cut -d" " -f 1`" retweets"
echo -e "- "`wc -l replies-$DAY.csv|cut -d" " -f 1`" replies"
echo -e "- "`wc -l favorites-$DAY.csv|cut -d" " -f 1`" favorites"

echo -e "\nDone\n"
